[manifest]
version = "1.0.0"

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if self.achievement_notification then "
position = "before"
payload = """
vsmod_drawVictoryNotif()
"""
match_indent = true