[manifest]
version = "1.0.0"

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """if G.GAME.chips - G.GAME.blind.chips >= 0 or G.GAME.current_round.hands_left < 1 then"""
position = "at"
payload = """
if vsmod_should_end_round() then
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = """if game_over then"""
position = "before"
payload = """
vsmod_round_ended(game_over)
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = """G:start_run(args)"""
position = "after"
payload = """
vsmod_run_start()
"""
match_indent = true