[manifest]
version = "1.0.0"

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = """check_for_unlock({type = 'chip_score', chips = math.floor(hand_chips*mult)})"""
position = "after"
payload = """
    onHandScored(hand_chips*mult)
"""
match_indent = false

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = """G.FUNCS.start_setup_run = function(e)"""
position = "after"
payload = """"""
match_indent = false