[manifest]
version = "1.0.0"

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = """check_for_unlock({type = 'chip_score', chips = math.floor(hand_chips*mult)})"""
position = "after"
payload = """
    onHandScored(hand_chips)
"""
match_indent = false